name: Gatsby Publish and Deploy

on:
  repository_dispatch:
    types: [build_and_deploy]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - run: npm install
    - run: npm run build  # or gatsby build
      env:
          GATSBY_SENDGRID_API_KEY: ${{ secrets.GATSBY_SENDGRID_API_KEY }}
          GATSBY_DATOCMS_API: ${{ secrets.GATSBY_DATOCMS_API }}
    - uses: actions/upload-artifact@v3
      with:
        name: public
        path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: public
        path: public
    - name: Deploy to FTP Server
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: s24.mydevil.net
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/
        local-dir: public/
