name: Gatsby Publish and Deploy

on:
  repository_dispatch:
    types: [build_and_deploy]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Ustawienie wersji Node.js
    - uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    # Sprawdzenie wersji Node.js
    - name: Check Node.js version
      run: node -v

    # Clear cache step
    - name: Clear cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          ~/.cache
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # Cache node_modules
    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    - run: npm install
    - run: npm run build  # or gatsby build
      env:
        GATSBY_DATOCMS_API: ${{ secrets.GATSBY_DATOCMS_API }}
        GATSBY_AIRTABLE_ACCESS_TOKEN: ${{ secrets.GATSBY_AIRTABLE_ACCESS_TOKEN }}
        GATSBY_AIRTABLE_BASE_ID: ${{ secrets.GATSBY_AIRTABLE_BASE_ID }}
        GATSBY_AIRTABLE_TABLE_NAME: ${{ secrets.GATSBY_AIRTABLE_TABLE_NAME }}
        GATSBY_SITE_URL: ${{ secrets.GATSBY_SITE_URL }}
        GATSBY_INPOST_API: ${{ secrets.GATSBY_INPOST_API }}

    - uses: actions/upload-artifact@v3
      with:
        name: public
        path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: public
        path: public
    - name: Deploy to FTP Server
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: s24.mydevil.net
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /
        local-dir: public/
